In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns',None)

In [4]:
#load dataset
df = pd.read_csv('/Users/aryaapalande/Desktop/Superstore_sales_project/superstore_data_raw/People-Table 1.csv')

In [5]:
#preview dataset
df.head()

    Regional Manager   Region  Unnamed: 2  Unnamed: 3  Unnamed: 4
0    Sadie Pawthorne     West         NaN         NaN         NaN
1        Chuck Magee     East         NaN         NaN         NaN
2  Roxanne Rodriguez  Central         NaN         NaN         NaN
3        Fred Suzuki    South         NaN         NaN         NaN

In [6]:
#dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Regional Manager  4 non-null      object
 1   Region            4 non-null      object
 2   Unnamed: 2        0 non-null      float64
 3   Unnamed: 3        0 non-null      float64
 4   Unnamed: 4        0 non-null      float64
dtypes: float64(3), object(2)
memory usage: 292.0+ bytes

In [7]:
df.columns

Index(['Regional Manager', 'Region', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [8]:
df.shape

(4, 5)

In [9]:
df.describe(include='all')

       Regional Manager Region  Unnamed: 2  Unnamed: 3  Unnamed: 4
count                 4      4         0.0         0.0         0.0
unique                4      4         NaN         NaN         NaN
top     Sadie Pawthorne   West         NaN         NaN         NaN
freq                  1      1         NaN         NaN         NaN
mean                NaN    NaN         NaN         NaN         NaN
std                 NaN    NaN         NaN         NaN         NaN
min                 NaN    NaN         NaN         NaN         NaN
25%                 NaN    NaN         NaN         NaN         NaN
50%                 NaN    NaN         NaN         NaN         NaN
75%                 NaN    NaN         NaN         NaN         NaN
max                 NaN    NaN         NaN         NaN         NaN

In [10]:
#check null values
df.isnull().sum()

Regional Manager    0
Region              0
Unnamed: 2          4
Unnamed: 3          4
Unnamed: 4          4
dtype: int64

In [11]:
#duplicated rows
df.duplicated().sum()

np.int64(0)

In [12]:
#remove unncessary columns
df = df[['Regional Manager','Region']]

In [13]:
df.columns

Index(['Regional Manager', 'Region'], dtype='object')

In [14]:
#count unique 
df.nunique()

Regional Manager    4
Region              4
dtype: int64

In [15]:
#frequency count
df['Region'].value_counts()

Region
West       1
East       1
Central    1
South      1
Name: count, dtype: int64

In [16]:
#save cleaned dataset
df.to_csv("/Users/aryaapalande/Desktop/Superstore_sales_project/superstore_data_cleaned/people_cleaned.csv", index=False)

In [17]:
import os
from sqlalchemy import create_engine

MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_HOST = os.getenv("MYSQL_HOST", "localhost")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE", "superstore")

engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"
)

In [18]:
df.to_sql(
    'People',
    engine,
    if_exists='replace',
    index=False
)

print("Orders data successfully loaded into MySQL.")

Orders data successfully loaded into MySQL.

In [19]:
import pandas as pd
pd.read_sql("SELECT COUNT(*) AS total_rows FROM Orders", engine)

   total_rows
0       10194

In [20]:
pd.read_sql("SELECT * FROM Orders LIMIT 5", engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Quarter,Shipping Days
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7